version: "2.3"
services:
  mqtt-bridge: 
    container_name: mqtt-bridge
    image: stjohnjohnson/smartthings-mqtt-bridge
    volumes:
      - ./mqtt-bridge:/config
    restart: always
    ports:
      - "192.168.10.41:8080:8080"
  hass:
    container_name: home-assistant
    network_mode: host
    image: homeassistant/home-assistant
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
