- alias: Someone Arrived
  trigger:
    platform: state
    entity_id: group.everyone
    from: not_home
    to: home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.morning
    - service: notify.sms
      data:
        message: "Someone is home!"
        target:
          - "+18608055785"
  condition: []

- alias: Everyone Leaves
  trigger:
    platform: state
    entity_id: group.everyone
    from: home
    to: not_home
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.sleep

- alias: Wake Up
  trigger:
    platform: time
    at: "05:00:00"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.early_morning

- alias: Up and Atom
  trigger:
    platform: time
    at: "06:00:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.morning
