homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.2834
  longitude: -71.3357
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  server_host: 192.168.10.42
  server_port: 80
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - sonos
#    - google_cast

hue:
  bridges:
    - host: 192.168.10.175

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
  - platform: openweathermap
    name: Weather
    api_key: !secret openweathermap_api_key
    forecast: 1
    monitored_conditions:
      - weather
      - temperature
      - wind_speed
      - humidity
      - clouds
      - rain
      - snow
  - platform: template
    sensors:
      weather_temp:
        friendly_name: Weather
        value_template: "{{ states('sensor.weather_temperature') | float }}"
  - platform: mqtt
    state_topic: "sensors/temp/bedroom"
    name: "Master Bedroom Temp"
    unit_of_measurement: "℉"
  - platform: mqtt
    state_topic: "sensors/temp/office"
    name: "Office Temp"
    unit_of_measurement: "℉"
  - platform: mqtt
    state_topic: "sensors/temp/recroom"
    name: "Rec Room Temp"
    unit_of_measurement: "℉"

binary_sensor:
    - platform: mqtt
      name: "Motion Sensor"
      state_topic: "smartthings/Motion Sensor/motion"
      payload_on: "active"
      payload_off: "inactive"
      device_class: "motion"

# Text to speech
tts:
  - platform: google

device_tracker:
  - platform: unifi_direct
    host: 192.168.10.70
    username: !secret unifi_username
    password: !secret unifi_password
    consider_home: 180
    interval_seconds: 60

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

mqtt:
  discovery: true
  discovery_prefix: smartthings
  broker: 192.168.10.41

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

notify:
  - name: sms
    platform: twilio_sms
    from_number: "+18607852006"
  - name: push
    platform: pushbullet
    api_key: !secret pushbullet_key

camera:
  - platform: generic
    name: House Temp
    still_image_url: "http://stats.gquad.space/render?majorGridLineColor=%23555555&from=-1hours&until=now&width=300&height=300&fontName=Courier&target=alias(movingAverage(stats.gauges.sensors.temp.office%2C12)%2C%22Office%22)&target=alias(movingAverage(stats.gauges.sensors.temp.recroom%2C12)%2C%22Rec%20Room%22)&target=alias(movingAverage(stats.gauges.sensors.temp.bedroom%2C12)%2C%22Bedroom%22)&fgcolor=000000&bgcolor=FFFFFF&fontSize=12&yMin=60&yMax=&title=House%20Temperatures&xFormat=%25I%3A%25M%20%25p&tz=America%2FNew_York&vtitle=Degrees%20Fahrenheit&minorGridLineColor=%23CCCCCC&_uniq=0.3979732907460245"

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

input_boolean:
  rec_room_heat:
    name: Enable Rec Room Heating
    initial: off
    icon: mdi:power

switch:
  - name: "Rec Room Camera"
    platform: mqtt
    command_topic: "smartthings/Rec Room Camera/switch"
    state_topic: "smartthings/Rec Room Camera/switch"
    payload_on: "on"
    payload_off: "off"
  - name: "First Floor Camera"
    platform: mqtt
    command_topic: "smartthings/First Floor Camera/switch"
    state_topic: "smartthings/First Floor Camera/switch"
    payload_on: "on"
    payload_off: "off"
  - name: "Porch Camera"
    platform: mqtt
    command_topic: "smartthings/Porch Camera/switch"
    state_topic: "smartthings/Porch Camera/switch"
    payload_on: "on"
    payload_off: "off"
  - platform: mqtt
    command_topic: "smartthings/Rec Room Heater/switch"
    state_topic: "smartthings/Rec Room Heater/switch"
    name: "Rec Room Heat"
    payload_on: "on"
    payload_off: "off"
    icon: mdi:radiator

light:
  - platform: mqtt
    brightness_state_topic: "smartthings/Rec Room Ceiling Lights/level"
    brightness_command_topic: "smartthings/Rec Room Ceiling Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Rec Room Ceiling Lights/switch"
    state_topic: "smartthings/Rec Room Ceiling Lights/switch"
    name: "Rec Room Ceiling Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Back Porch Light/level"
    brightness_command_topic: "smartthings/Back Porch Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Back Porch Light/switch"
    state_topic: "smartthings/Back Porch Light/switch"
    name: "Back Porch Light"
  - platform: mqtt
    brightness_state_topic: "smartthings/Bedroom Ceiling Lights/level"
    brightness_command_topic: "smartthings/Bedroom Ceiling Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Bedroom Ceiling Lights/switch"
    state_topic: "smartthings/Bedroom Ceiling Lights/switch"
    name: "Bedroom Ceiling Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Nathan's Light/level"
    brightness_command_topic: "smartthings/Nathan's Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Nathan's Light/switch"
    state_topic: "smartthings/Nathan's Light/switch"
    name: "Nathan's Light"
  - platform: mqtt
    brightness_state_topic: "smartthings/Christmas Lights/level"
    brightness_command_topic: "smartthings/Christmas Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Christmas Lights/switch"
    state_topic: "smartthings/Christmas Lights/switch"
    name: "Christmas Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Dining Room Ceiling Light/level"
    brightness_command_topic: "smartthings/Dining Room Ceiling Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Dining Room Ceiling Light/switch"
    state_topic: "smartthings/Dining Room Ceiling Light/switch"
    name: "Dining Room Ceiling Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Front Porch Light/level"
    brightness_command_topic: "smartthings/Front Porch Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Front Porch Light/switch"
    state_topic: "smartthings/Front Porch Light/switch"
    name: "Front Porch Light"
  - platform: mqtt
    brightness_state_topic: "smartthings/Hallway Light/level"
    brightness_command_topic: "smartthings/Hallway Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Hallway Light/switch"
    state_topic: "smartthings/Hallway Light/switch"
    name: "Hallway Light"
  - platform: mqtt
    brightness_state_topic: "smartthings/Kitchen Ceiling Lights/level"
    brightness_command_topic: "smartthings/Kitchen Ceiling Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Kitchen Ceiling Lights/switch"
    state_topic: "smartthings/Kitchen Ceiling Lights/switch"
    name: "Kitchen Ceiling Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Kitchen Counter Lights/level"
    brightness_command_topic: "smartthings/Kitchen Counter Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Kitchen Counter Lights/switch"
    state_topic: "smartthings/Kitchen Counter Lights/switch"
    name: "Kitchen Counter Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Landing Lights/level"
    brightness_command_topic: "smartthings/Landing Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Landing Lights/switch"
    state_topic: "smartthings/Landing Lights/switch"
    name: "Landing Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Laundry Room Lights/level"
    brightness_command_topic: "smartthings/Laundry Room Lights/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Laundry Room Lights/switch"
    state_topic: "smartthings/Laundry Room Lights/switch"
    name: "Laundry Room Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Living Room Ceiling Light/level"
    brightness_command_topic: "smartthings/Living Room Ceiling Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Living Room Ceiling Light/switch"
    state_topic: "smartthings/Living Room Ceiling Light/switch"
    name: "Living Room Ceiling Lights"
  - platform: mqtt
    brightness_state_topic: "smartthings/Office Ceiling Light/level"
    brightness_command_topic: "smartthings/Office Ceiling Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Office Ceiling Light/switch"
    state_topic: "smartthings/Office Ceiling Light/switch"
    name: "Office Ceiling Light"
  - platform: mqtt
    brightness_state_topic: "smartthings/Walkout Light/level"
    brightness_command_topic: "smartthings/Walkout Light/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    command_topic: "smartthings/Walkout Light/switch"
    state_topic: "smartthings/Walkout Light/switch"
    name: "Walkout Light"

# Template
#  - platform: mqtt
#    brightness_state_topic: "smartthings//level"
#    brightness_command_topic: "smartthings//level"
#    brightness_scale: 100
#    payload_on: "on"
#    payload_off: "off"
#    command_topic: "smartthings//switch"
#    state_topic: "smartthings//switch"
#    name: ""
